# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subexperiment.', max_length=100)),
                ('number', models.IntegerField(help_text='Number of the subexperiment.')),
                ('description', models.TextField(blank=True, help_text='Short description of the experiment (optional).', max_length=1000)),
                ('note', models.TextField(blank=True, help_text='Additional notes on the subexperiment (optional).', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='First and last name.', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Notes (optional).', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='contactperson',
            field=models.ForeignKey(help_text='Main contact person for this subexperiment.', on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        ),
    ]
