# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_auto_20160310_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, help_text='Email address(es) (optional).', max_length=200),
        ),
    ]
