# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='time_removed',
            field=models.DateTimeField(help_text='Time when the drive was removed from the drive bay.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='experiment',
            field=models.ManyToManyField(blank=True, help_text='The subexperiment this file belongs to (optional).', null=True, to='dataentry.Experiment'),
        ),
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.ForeignKey(blank=True, help_text='Format of the file (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Format'),
        ),
        migrations.AlterField(
            model_name='file',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where the recording took place (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Location'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Sensor used to obtain the data (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Sensor'),
        ),
        migrations.AlterField(
            model_name='file',
            name='time_added',
            field=models.DateTimeField(blank=True, help_text='Time when the drive was added to the drive bay (optional).'),
        ),
    ]
