# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_auto_20160311_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivecopy',
            name='drive',
            field=models.ForeignKey(default=1, help_text='The unique drive it is a copy of.', on_delete=django.db.models.deletion.CASCADE, to='dataentry.Drive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='time_added',
            field=models.DateTimeField(auto_now=True, help_text='Time when the drive was added to the drive bay (optional).'),
        ),
    ]
