# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0007_auto_20160311_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the data source (e.g., 'Local Police')", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The data source (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Source'),
        ),
    ]
