# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0008_auto_20160314_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='experiment',
            field=models.ManyToManyField(blank=True, help_text='The subexperiment this file belongs to (optional).', to='dataentry.Experiment'),
        ),
    ]
