# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0009_auto_20160314_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the data source (e.g., 'Local Police')", max_length=200)),
            ],
        ),
    ]
