# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0010_source2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source2',
        ),
    ]
