# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0011_delete_source2'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes on this data source (optional).', max_length=1000),
        ),
    ]
