# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0013_auto_20160315_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='external',
            field=models.BooleanField(default=False, help_text='True when the drive is external and false otherwise.'),
        ),
    ]
