# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0015_auto_20160329_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='whereabouts',
            field=models.TextField(blank=True, help_text='Whereabouts of this drive copy, e.g., who had it lasts, where is it now etc. (optional).', max_length=1000),
        ),
    ]
